baseURL = "/"
enableRobotsTXT = true
languageCode = "en-us"
title = "Coteams"
[sitemap]
  changefreq = "monthly"
  priority = 1
  filename = "sitemap.xml"
[params]
favicon = "/static/images/favicon.svg"
