baseURL = "/"
languageCode = "en-us"
title = "Coteams"
[[menu.sidebar]]
    name = "Profile Summary"
    url = "/how-it-works/profile-summary/profile-summary/"
[[menu.sidebar]]
    name = "About Me"
    url = "/how-it-works/about-me/about-me/"
[[menu.sidebar]]
    name = "Availability"
    url = "/how-it-works/availability/availability/"