baseURL = "/"
enableRobotsTXT = true
languageCode = "en-us"
title = "Coteams"
[sitemap]
  changefreq = "monthly"
  priority = 1
  filename = "sitemap.xml"
[params]
favicon = "/static/images/favicon.svg"
[menu.sidebar]
    name = "General"
    weight = 1
[menu.sidebar]
    name = "For Talents"
    weight = 2
[menu.sidebar]
    name = "For Clients"
    weight = 3
[menu.sidebar]
    name = "For Teams"
    weight = 4
