baseURL = "http://example.org/"
languageCode = "en-us"
title = "Coteams"
[[menu.main]]
SectionPagesMenu = "main"
name = "getting started"
url = "/getting-started/"
weight = 1
[[menu.main]]
name = "Privet"
url = "/about/"
weight = 2
