baseURL = "/"
enableRobotsTXT = true
languageCode = "en-us"
title = "Coteams"
[[menu.sidebar]]
name = "Profile settings"
parent = "General"
url = "#"
weight = 3
[[menu.sidebar]]
name = "Authentication"
parent = "General"
url = "#"
weight = 2
[[menu.sidebar]]
name = "Registration"
parent = "General"
url = "#"
weight = 1
[[menu.sidebar]]
name = "For Talents"
weight = 5
[[menu.sidebar]]
name = "For Clients"
weight = 4
[[menu.sidebar]]
name = "For Teams"
url = "#"
weight = 3
[[menu.sidebar]]
name = "General"
url = "#"
weight = 1
[params]
favicon = "/static/images/favicon.svg"
[sitemap]
changefreq = "monthly"
filename = "sitemap.xml"
priority = 1
