baseURL = "http://example.org/"
languageCode = "en-us"
title = "Coteams"
[[menu.main]]
    title = "about hugo"
    url = "/about/"
[[menu.main]]
    title = "getting started"
    url = "/getting-started/"