baseURL = "http://example.org/"
languageCode = "en-us"
title = "Coteams"
[[menu.main]]
    name = "about hugo"
    url = "/about/"
[[menu.main]]
    name = "getting started"
    url = "/getting-started/"
SectionPagesMenu = "main"