baseURL = "/"
enableRobotsTXT = true
languageCode = "en-us"
title = "Coteams"
[[menu.sidebar]]
name = "Messaging"
parent = "General"
url = "/help/general/messaging"
weight = 5
[[menu.sidebar]]
name = "Image Upload"
parent = "General"
url = "/help/general/image-upload"
weight = 4
[[menu.sidebar]]
name = "Profile settings"
parent = "General"
url = "/help/general/profile-settings"
weight = 3
[[menu.sidebar]]
name = "Authentication"
parent = "General"
url = "/help/general/authentication"
weight = 2
[[menu.sidebar]]
name = "Sign Up via Social Accounts (Google, Facebook, LinkedIn)"
parent = "Registration"
url = "#"
weight = 3
[[menu.sidebar]]
name = "Sign Up via Email"
parent = "Registration"
url = "#"
weight = 2
[[menu.sidebar]]
name = "General Information for Sign Up"
parent = "Registration"
url = "#"
weight = 1
[[menu.sidebar]]
identifier = "registration"
name = "Registration"
parent = "General"
url = "/help/general/registration"
weight = 1
[[menu.sidebar]]
identifier = "general"
name = "General"
weight = 1
[[menu.sidebar]]
name = "For Teams"
weight = 4
[[menu.sidebar]]
name = "For Clients"
weight = 3
[[menu.sidebar]]
name = "For Talents"
weight = 2
[params]
favicon = "/static/images/favicon.svg"
[sitemap]
changefreq = "monthly"
filename = "sitemap.xml"
priority = 1
