baseURL = "https://coteams.co/"
enableRobotsTXT = true
languageCode = "en-us"
title = "Coteams"
[sitemap]
  changefreq = "monthly"
  priority = 1
  filename = "sitemap.xml"
[Taxonomies]
  tag = "tags"
[[menu.secondary]]
name = "Search"
url = "/search/"
weight = 1
[params]
favicon = "/static/images/favicon.svg"
