baseURL = "/"
enableRobotsTXT = true
languageCode = "en-us"
title = "Coteams"
[sitemap]
  changefreq = "monthly"
  priority = 0.8
  filename = "sitemap.xml"
[[menu.secondary]]
name = "Search"
url = "/search/"
weight = 1
[params]
favicon = "/static/images/favicon.svg"
