backend:
  name: github
  repo: Ae3232/headless-cms
  branch: main

publish_mode: editorial_workflow
media_folder: "static/images"
public_folder: "/images"
media_library:
  name: uploadcare
  config:
    publicKey: 770d59abb88e58b8d65c

collections:
  - name: 'about-us'
    label: 'about-us'
    folder: 'content/about-us'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields: # The fields for each document, usually in front matter
      - {label: "title", name: "title", widget: "markdown", default: "editor_components"}
      - {label: "url", name: "url", widget: "file", default: "editor_components"}
      - {label: "Permalink", name: "permalink", widget: "string"}
      - {label: "description", name: "description", widget: "markdown"}
      - {label: "topSectionImg", name: "topSectionImg", widget: "image"}
      - {label: "topSectionTitle", name: "topSectionTitle", widget: "markdown"}