backend:
  name: github
  repo: Ae3232/headless-cms
  branch: main

publish_mode: editorial_workflow
media_folder: "static/images"
public_folder: "/images"
media_library:
  name: uploadcare
  config:
    publicKey: 770d59abb88e58b8d65c

collections:
  - label: "Settings"
    name: "settings"
    files:
      - label: "Navigation Top"
      - name: "navigation"
      - file: "content/navigation/_index.md"
        fields:
          - label: "Navigation Top List"
            name: "menu"
            widget: list
            fields:
              - { label: Name, name: name, widget: string }
              - { label: Path, name: url, widget: string }
              - { label: Position, name: weight, widget: string }
  - label: "Pages"
    name: "page"
    files:
      - label: "index"
        name: "index"
        file: "content/_index.md"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Description, name: description, widget: markdown}
          - { label: topSectionImg, name: topSectionImg, widget: image }
          - { label: topSectionTitle, name: topSectionTitle, widget: markdown }
          - { label: topSectionDescription, name: topSectionDescription, widget: markdown }
      - label: "About Us"
        name: "about-us"
        file: "content/about-us/_index.md"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Description, name: description, widget: markdown }
          - { label: topSectionImg, name: topSectionImg, widget: image }
          - { label: topSectionTitle, name: topSectionTitle, widget: markdown }
          - { label: topSectionDescription, name: topSectionDescription, widget: markdown }
      - label: "For Clients"
        name: "for-clients"
        file: "content/for-clients/_index.md"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Description, name: description, widget: markdown }
          - { label: topSectionImg, name: topSectionImg, widget: image }
          - { label: topSectionTitle, name: topSectionTitle, widget: markdown }
          - { label: topSectionDescription, name: topSectionDescription, widget: markdown }
      - label: "For Talents"
        name: "for-talents"
        file: "content/for-talents/_index.md"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Description, name: description, widget: markdown }
          - { label: topSectionImg, name: topSectionImg, widget: image }
          - { label: topSectionTitle, name: topSectionTitle, widget: markdown }
          - { label: topSectionDescription, name: topSectionDescription, widget: markdown }