---
new_page_extension: html
auto_deploy: false
admin_path: "/static/admin"
webhook_url: https://app.forestry.io/git/bitbucket/hook
sections:
- type: directory
  path: content/for-clients
  label: For Clients
  create: all
  match: "**/*"
  templates:
  - for-clients
- type: directory
  path: content
  label: index
  create: all
  match: "*"
  templates:
  - home-page-fm
upload_dir: static
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":year:/:month:/:day:/:filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.79.0
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  instant_preview_command: hugo server -D -E -F --renderToDisk -d public
version: 0.79.0
