upload_path: "/static/uploads/:year:/:month:/:day:"
frontmatter_file_url_template: "/uploads/:year:/:month:/:day:"
body_file_url_template: "/uploads/:year:/:month:/:day:"
new_page_extension: html
auto_deploy: false
admin_path: "/static/admin"
webhook_url: https://app.forestry.io/git/bitbucket/hook
sections:

  - path: content
    label: Pages
    create: all
    # Imported pages without a FMT assigned
    # will automatically use "pages"

version: 0.79.0
---
