---
new_page_extension: md
auto_deploy: false
admin_path: "/static/admin"
webhook_url: https://app.forestry.io/git/bitbucket/hook
sections:
- type: directory
  path: content
  label: Home Page
  create: all
  match: "*"
  templates:
  - home-page-fm
- type: directory
  path: content/for-clients
  label: For Talents
  create: all
  match: "**/*"
  templates:
  - for-clients
- type: directory
  path: content/help
  label: Help
  create: all
  match: "**/*"
  templates:
  - help
- type: directory
  path: content/privacy-policy
  label: Privacy Policy
  create: all
  match: "**/*"
  templates:
  - privacy-policy
upload_dir: static
public_path: ''
front_matter_path: ''
use_front_matter_path: true
file_template: ":year:/:month:/:day:/:filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.79.0
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  instant_preview_command: hugo server -D -E -F --renderToDisk -d public
version: 0.79.0
